CREATE INDEX "artifacts_item_add_timestamp_idx" ON "artifacts"."item" USING btree( "add_timestamp" DESC NULLS LAST );
CREATE INDEX "artifacts_item_id_idx" ON "artifacts"."item" USING btree( "id" ASC NULLS LAST );
CREATE INDEX "artifacts_item_is_on_homepage_add_timestamp" ON "artifacts"."item" USING btree( "is_on_homepage" DESC NULLS FIRST, "add_timestamp" DESC NULLS LAST );
CREATE INDEX "artifacts_item_is_on_homepage_idx" ON "artifacts"."item" USING btree( "is_on_homepage" ASC NULLS LAST );
CREATE INDEX "artifacts_item_search_data_gin_idx" ON "artifacts"."item" USING gin( "search_data" );
CREATE INDEX "artifacts_item_search_data_idx" ON "artifacts"."item" USING btree( "search_data" ASC NULLS LAST );
CREATE INDEX "artifacts_item_tags_gin_idx" ON "artifacts"."item" USING gin( "tags" );
CREATE INDEX "artifacts_item_thumbs_list" ON "artifacts"."item" USING btree( "is_public" ASC NULLS LAST, "is_removed" ASC NULLS LAST, "is_imported" ASC NULLS LAST, "id" DESC NULLS FIRST );
CREATE INDEX "item_author_account_id_idx" ON "artifacts"."item" USING btree( "author_account_id" ASC NULLS LAST );
CREATE INDEX "itemIdx" ON "artifacts"."item" USING btree( "is_public" ASC NULLS LAST, "is_removed" ASC NULLS LAST, "is_age_restricted" ASC NULLS LAST );
CREATE INDEX "item_elementIdx" ON "artifacts"."item_element" USING btree( "item_id" ASC NULLS LAST, "ordering" ASC NULLS LAST );
CREATE INDEX "artifacts_item_element_image_data_item_element_id_idx" ON "artifacts"."item_element_image_data" USING btree( "item_element_id" ASC NULLS LAST );
CREATE INDEX "artifacts_item_element_mem_data_item_element_id_idx" ON "artifacts"."item_element_mem_data" USING btree( "item_element_id" ASC NULLS LAST );
CREATE INDEX "artifacts_item_element_ytvideo_data_item_element_id_idx" ON "artifacts"."item_element_ytvideo_data" USING btree( "item_element_id" ASC NULLS LAST );
CREATE INDEX "index_id" ON "artifacts"."meme_background" USING btree( "id" ASC NULLS LAST );
CREATE INDEX "index_search_data" ON "artifacts"."meme_background" USING btree( "search_data" ASC NULLS LAST );
CREATE INDEX "index_uses_count" ON "artifacts"."meme_background" USING btree( "uses_count" ASC NULLS LAST );
CREATE INDEX "artifacts_tag_elements_count_idx" ON "artifacts"."tag" USING btree( "elements_count" ASC NULLS LAST );
CREATE INDEX "artifacts_tag_id_idx" ON "artifacts"."tag" USING btree( "id" ASC NULLS LAST );
CREATE INDEX "index_is_removed" ON "artifacts"."tag" USING btree( "is_removed" ASC NULLS LAST );
CREATE INDEX "searcher_query_id_idx" ON "searcher"."query" USING btree( "id" ASC NULLS LAST );
CREATE INDEX "searcher_query_is_have_results_idx" ON "searcher"."query" USING btree( "is_have_results" ASC NULLS LAST );
CREATE INDEX "searcher_query_last_use_timestamp_idx" ON "searcher"."query" USING btree( "last_use_timestamp" DESC NULLS LAST );
CREATE INDEX "searcher_query_slug_idx" ON "searcher"."query" USING btree( "slug" ASC NULLS LAST );
CREATE INDEX "users_account_display_name_idx" ON "users"."account" USING btree( "display_name" ASC NULLS LAST );
CREATE INDEX "users_account_id_idx" ON "users"."account" USING btree( "id" ASC NULLS LAST );
